### ISSUE TITLE
Can't get the application to work.

### ISSUE THREAD

**Issue by jozig1234** [codepalmz/BlockchainMedicalSystem_dapp#3]
Hello!

My name is Joseph Jourekian. I'm a 4th year student at the University of Windsor and I'm currently working on a research project about blockchains with a partner. I wanted to use your project as a foundation for mine. However, I am having issues getting the project to work. The program launches successfully but ganache-cli is not prompting me to input the mnemonic seed phrase. Plus once I connected to the url with metamask and I try to input data I click on the Add record button and nothing happens. Can you help me with this?

**Comment by ArumdawoCode** [comment]
Hey Joseph!

Nice meeting you! Thanks for reaching out! Also, I will help as much as I can to make it work for you.
Hope you are doing fine! Kindly send a screenshot of what you are getting from the ganache-cli and also that of metamask so I can assist with making it work for you. Looking forward to your response.

Although I w
Also, I look forward to seeing your work.

Cheers

**Comment by jozig1234** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/4513043/67977516-a4f7c400-fbee-11e9-83ba-bb247e2b35b9.png)
![Screenshot (9)](https://user-images.githubusercontent.com/4513043/67977517-a4f7c400-fbee-11e9-8bf9-53d30a19cb35.png)

**Comment by jozig1234** [comment]
Here are the screenshots. Basically, once I input npm run dev and the application starts up, I can't do anything after that. The next step says to put the copied mnemonic seed when prompted but I'm never prompted. MetaMask does connect properly.

Thank you!

**Comment by jozig1234** [comment]
Any idea of what I can do to get this fixed?

**Comment by jozig1234** [comment]
@ArumdawoCode

**Comment by preyalprajapati** [comment]
Hello, I am having the same issue while trying the code.
Metamask wallet is connected but while adding patients, just a prompt of hello there occurs and it does not move forward. 
If you could just guide me through the issue, it will be of immense help !
